debug: false

settings:
  bypass-permission: "anarchyruleengine.bypass"

items:

  trap:
    material: STICK
    name: "&cТрапка"
    lore:
      - "&7Тестовый предмет"

  plast:
    material: BLAZE_ROD
    name: "&6Пласт"
    lore:
      - "&7Еще один тестовый предмет"

rules:
  spawn-right-click-test:
    enabled: true
    priority: 100
    stop-processing: true

    conditions:
      item: trap
      region: spawn
      interaction-action: RIGHT_CLICK_BLOCK

    actions:
      - type: message
        message: "&aТрапка использована!"

      - type: remove-item
        amount: 1

      - type: cancel