debug: false

settings:
  bypass-permission: "anarchyruleengine.bypass"

items: {}

rules:
  # deny-diamond:
  #   enabled: true
  #   priority: 100
  #   stop-processing: true
  #   conditions:
  #     material: DIAMOND
  #     permission: "anarchyruleengine.diamond"
  #   actions:
  #     - type: message
  #       message: "&cYou cannot use diamonds here."
  #     - type: cancel
